apiVersion: apps/v1
kind: Deployment

metadata:
  name: ogbv-ml-rest
  labels:
    app.kubernetes.io/name: ogbv-ml-rest

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ogbv-ml-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ogbv-ml-rest

    spec:
      volumes:
        - name: ogbv-ml-rest-cache
          persistentVolumeClaim:
            claimName: ogbv-ml-rest-cache
        - name: ogbv-ml-rest-assets
          persistentVolumeClaim:
            claimName: ogbv-ml-rest-assets
      containers:
        - name: ogbv-ml-rest
          image: tattletech/ogbv-ml-rest:7513013
          resources:
            limits:
              cpu: 1230m
              memory: 8Gi
          imagePullPolicy: Always
          command: ["sh", "main.sh"]
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/root/.cache/huggingface/transformers"
              name: ogbv-ml-rest-cache
            - mountPath: "/app/assets"
              name: ogbv-ml-rest-assets
