apiVersion: v1
kind: Service
metadata:
  name: ogbv-ml-rest
  labels:
    app.kubernetes.io/name: ogbv-ml-rest
spec:
  selector:
    app.kubernetes.io/name: ogbv-ml-rest
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
